use anyhow::Result;
use console::Style;

use aegis_core::config::{deploy_config, undeploy_config};
use aegis_core::manifest::LinkStrategy;
use aegis_core::module::HookEvent;
use aegis_core::template;
use aegis_core::variables::resolve_variables;

use super::Context;

#[derive(clap::Args)]
pub struct LinkArgs {
 /// Only link a specific module
 #[arg(long)]
 pub module: Option<String>,
}

#[derive(clap::Args)]
pub struct UnlinkArgs {
 /// Only unlink a specific module
 #[arg(long)]
 pub module: Option<String>,
}

/// Generate shell snippet content for environment variables.
fn generate_env_snippet(module_name: &str, module_path: &str, env_vars: &[aegis_core::module::EnvVar]) -> String {
 let mut lines = vec![
  "# AUTO-GENERATED by aegis — do not edit.".to_string(),
  format!("# Module: {module_name}"),
  format!("# Source: {module_path}/module.toml"),
 ];

 for env_var in env_vars {
  if env_var.prepend_path {
   lines.push(format!(r#"export {}="{}:${}""#, env_var.name, env_var.value, env_var.name));
  } else {
   lines.push(format!(r#"export {}="{}""#, env_var.name, env_var.value));
  }
 }

 lines.join("\n") + "\n"
}

#[cfg(test)]
mod tests {
 use super::*;
 use aegis_core::module::EnvVar;

 #[test]
 fn test_generate_env_snippet_plain_export() {
  let envs = vec![EnvVar {
   name: "FOO".into(),
   value: "bar".into(),
   prepend_path: false,
  }];
  let out = generate_env_snippet("test-mod", "/tmp/modules/test-mod", &envs);
  assert!(out.contains("# Module: test-mod"));
  assert!(out.contains("# Source: /tmp/modules/test-mod/module.toml"));
  assert!(out.contains(r#"export FOO="bar""#));
 }

 #[test]
 fn test_generate_env_snippet_prepend_path() {
  // prepend_path=true should produce: export PATH="new:$PATH" (self-referential)
  let envs = vec![EnvVar {
   name: "PATH".into(),
   value: "/usr/local/go/bin".into(),
   prepend_path: true,
  }];
  let out = generate_env_snippet("go", "/tmp/modules/go", &envs);
  assert!(out.contains(r#"export PATH="/usr/local/go/bin:$PATH""#),
   "expected PATH prepend format, got:\n{}", out);
 }

 #[test]
 fn test_generate_env_snippet_multiple_entries() {
  let envs = vec![
   EnvVar { name: "GOPATH".into(), value: "$HOME/go".into(), prepend_path: false },
   EnvVar { name: "PATH".into(), value: "/usr/local/go/bin:$HOME/go/bin".into(), prepend_path: true },
  ];
  let out = generate_env_snippet("languages", "/opt/aegis/example/modules/languages", &envs);
  let lines: Vec<&str> = out.lines().collect();
  // 3 header lines + 2 export lines = 5
  assert_eq!(lines.len(), 5, "expected 5 lines, got {}: {:?}", lines.len(), lines);
  assert!(lines[3].contains("GOPATH"));
  assert!(lines[4].contains("PATH"));
  assert!(lines[4].contains("$PATH")); // prepend form
 }

 #[test]
 fn test_generate_env_snippet_trailing_newline() {
  let envs = vec![EnvVar {
   name: "X".into(),
   value: "y".into(),
   prepend_path: false,
  }];
  let out = generate_env_snippet("m", "/tmp/m", &envs);
  assert!(out.ends_with('\n'), "snippet should end with newline");
 }
}

pub async fn run_link(args: LinkArgs, ctx: &Context) -> Result<()> {
 let (manifest, manifest_dir) = ctx.load_manifest()?;
 let modules = ctx.load_modules(&manifest, &manifest_dir, args.module.as_deref())?;

 let profile = manifest.active_profile(ctx.profile.as_deref());
 let profile_vars = profile
  .map(|(_, p)| p.variables.clone())
  .unwrap_or_default();
 let variables = resolve_variables(&manifest.variables, &profile_vars)?;

 let green = Style::new().green().bold();
 let mut linked = 0;

 // Get home directory for bashrc.d
 let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("Could not determine home directory"))?;
 let bashrc_d = home.join(".bashrc.d");

 for module in &modules {
  // Run pre-link hooks
  for hook in module.hooks_for(HookEvent::PreLink) {
   if !ctx.dry_run {
    let status = std::process::Command::new("sh")
     .args(["-c", &hook.command])
     .status()?;
    if !status.success() {
     tracing::warn!("pre-link hook failed: {}", hook.command);
    }
   }
  }

  for cfg in &module.manifest.configs {
   if !cfg.applies_to_current_os() {
    continue;
   }
   let source = module.config_source_path(cfg);
   let target = module.config_target_path(cfg)?;
   let strategy = module.effective_strategy(cfg, manifest.aegis.strategy);

   match strategy {
    LinkStrategy::Template => {
     // Render the template to a temp file, then deploy as copy
     let rendered = template::render_file(&source, &variables)?;
     if ctx.dry_run {
      println!(
       "[dry-run] would render template {} → {}",
       source.display(),
       target.display()
      );
     } else {
      if let Some(parent) = target.parent() {
       std::fs::create_dir_all(parent)?;
      }
      std::fs::write(&target, rendered)?;
      tracing::info!("rendered {} → {}", source.display(), target.display());
     }
    }
    _ => {
     deploy_config(&source, &target, strategy, ctx.dry_run)?;
    }
   }
  }

  // Handle environment variables
  if !module.manifest.env.is_empty() {
   let snippet_path = bashrc_d.join(format!("aegis-{}.sh", module.name));
   let snippet_content = generate_env_snippet(
    &module.name,
    &module.base_path.display().to_string(),
    &module.manifest.env,
   );

   if ctx.dry_run {
    println!(
     "[dry-run] would write {} ({})",
     snippet_path.display(),
     snippet_content.lines().count()
    );
   } else {
    // Create bashrc.d directory if needed
    if !bashrc_d.exists() {
     std::fs::create_dir_all(&bashrc_d)?;
    }

    // Check if content is identical (idempotent)
    let existing = std::fs::read_to_string(&snippet_path).unwrap_or_default();
    if existing != snippet_content {
     std::fs::write(&snippet_path, &snippet_content)?;
     tracing::info!(
      "wrote env snippet {} ({} lines)",
      snippet_path.display(),
      snippet_content.lines().count()
     );
    } else {
     tracing::debug!("env snippet unchanged: {}", snippet_path.display());
    }
   }
  }

  linked += 1;

  // Run post-link hooks
  for hook in module.hooks_for(HookEvent::PostLink) {
   if !ctx.dry_run {
    let status = std::process::Command::new("sh")
     .args(["-c", &hook.command])
     .status()?;
    if !status.success() {
     tracing::warn!("post-link hook failed: {}", hook.command);
    }
   }
  }
 }

 println!(
  "{} Linked {linked} config(s) across {} module(s)",
  green.apply_to("✓"),
  modules.len()
 );
 Ok(())
}

pub async fn run_unlink(args: UnlinkArgs, ctx: &Context) -> Result<()> {
 let (manifest, manifest_dir) = ctx.load_manifest()?;
 let modules = ctx.load_modules(&manifest, &manifest_dir, args.module.as_deref())?;

 let green = Style::new().green().bold();
 let mut unlinked = 0;

 // Get home directory for bashrc.d
 let home = dirs::home_dir().ok_or_else(|| anyhow::anyhow!("Could not determine home directory"))?;
 let bashrc_d = home.join(".bashrc.d");

 for module in &modules {
  for hook in module.hooks_for(HookEvent::PreUnlink) {
   if !ctx.dry_run {
    let status = std::process::Command::new("sh")
     .args(["-c", &hook.command])
     .status()?;
    if !status.success() {
     tracing::warn!("pre-unlink hook failed: {}", hook.command);
    }
   }
  }

  for cfg in &module.manifest.configs {
   if !cfg.applies_to_current_os() {
    continue;
   }
   let target = module.config_target_path(cfg)?;
   undeploy_config(&target, ctx.dry_run)?;
   unlinked += 1;
  }

  // Remove stale env snippet if module has no env vars
  let snippet_path = bashrc_d.join(format!("aegis-{}.sh", module.name));
  if snippet_path.exists() {
   if ctx.dry_run {
    println!("[dry-run] would remove stale env snippet {}", snippet_path.display());
   } else {
    std::fs::remove_file(&snippet_path)?;
    tracing::info!("removed stale env snippet {}", snippet_path.display());
   }
  }

  for hook in module.hooks_for(HookEvent::PostUnlink) {
   if !ctx.dry_run {
    let status = std::process::Command::new("sh")
     .args(["-c", &hook.command])
     .status()?;
    if !status.success() {
     tracing::warn!("post-unlink hook failed: {}", hook.command);
    }
   }
  }
 }

 println!(
  "{} Unlinked {unlinked} config(s) across {} module(s)",
  green.apply_to("✓"),
  modules.len()
 );
 Ok(())
}
